services:
  # --- 1. Local PostgreSQL Database ---
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # No healthcheck here for now

  # --- 2. Auth Service (Python) ---
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file: ./.env
    depends_on: # Simplified depends_on
      - postgres-db
    # No healthcheck

  # --- 3. Project Service (Python) ---
  project-service:
    build: ./services/project-service
    container_name: project-service
    env_file: ./.env
    depends_on: # Simplified depends_on
      - postgres-db
    # No healthcheck

  # --- 4. AI Core Service (Python) ---
  ai-core-service:
    build: ./services/ai-core-service
    container_name: ai-core-service
    env_file: ./.env
    # No healthcheck

  # --- 5. Analysis Service (Python) ---
  analysis-service:
    build: ./services/analysis-service
    container_name: analysis-service
    env_file: ./.env
    depends_on: # Simplified depends_on
      - ai-core-service
    # No healthcheck

  # --- 6. Frontend Service (Node.js + React) ---
  frontend-service:
    build: ./services/frontend-dashboard-service
    container_name: frontend-service
    env_file: ./.env
    ports:
      - "3000:5000"
    depends_on: # Simplified depends_on list
      - auth-service
      - project-service
      - analysis-service
      - ai-core-service
    # No healthcheck

volumes:
  postgres_data: