# This file creates a persistent 1GB "virtual hard drive" for our database.
# This ensures that if the database pod restarts, the data is not lost.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc # Persistent Volume Claim
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted by one pod at a time
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage