# 1. Kubernetes Service Account (linked to GCP 'terraform-sa' by annotation)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-workload-identity-sa
  annotations:
    # This links K8s SA to GCP SA. Pipeline replaces the placeholder.
    iam.gke.io/gcp-service-account: "terraform-sa@PLACEHOLDER_PROJECT_ID.iam.gserviceaccount.com"
  namespace: default
---
# 2. Kubernetes Secret for Database Credentials
# The CI/CD pipeline will find this secret and inject the Base64-encoded values
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Placeholders for the pipeline's 'sed' command to replace
  DB_USER: {{secrets.DB_USER}}
  DB_PASSWORD: {{secrets.DB_PASSWORD}}
