# --- Project Service Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      serviceAccountName: app-workload-identity-sa # Use the same secure SA
      containers:
      # --- Main Project Service Container ---
      - name: project-service
        image: PLACEHOLDER_REGION-docker.pkg.dev/PLACEHOLDER_PROJECT_ID/aiforge-services/project-service:PLACEHOLDER_TAG
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DATABASE_URL
          value: "postgresql+psycopg2://$(DB_USER):$(DB_PASSWORD)@/aiforge-main-db?host=/cloudsql/PLACEHOLDER_PROJECT_ID:PLACEHOLDER_REGION:aiforge-db-instance"
        - name: JWT_SECRET_KEY
          value: "a-very-strong-and-long-secret-key-for-your-jwt-tokens" # Must match auth-service
        - name: ALGORITHM
          value: "HS256"
        volumeMounts:
          - name: cloudsql-socket-volume
            mountPath: /cloudsql
            readOnly: false

      # --- Cloud SQL Auth Proxy Sidecar Container ---
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        args:
          - "--structured-logs"
          - "--private-ip"
          - "--unix-socket=/cloudsql"
          - "PLACEHOLDER_PROJECT_ID:PLACEHOLDER_REGION:aiforge-db-instance"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - name: cloudsql-socket-volume
            mountPath: /cloudsql
            readOnly: false

      volumes:
        - name: cloudsql-socket-volume
          emptyDir: {}
---
# --- Project Service ClusterIP (Internal DNS: "project-service") ---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
