name: CI/CD Pipeline - Build, Scan, Deploy to GKE

# --- TRIGGERS ---
on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

# --- ENVIRONMENT VARIABLES ---
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GKE_CLUSTER: aiforge-cluster
  GAR_LOCATION: ${{ secrets.GCP_REGION }}-docker.pkg.dev
  GAR_REPOSITORY: aiforge-services
  # CORRECTED: Includes 'frontend-dashboard-service'
  SERVICE_NAMES: "auth-service project-service ai-core-service analysis-service frontend-dashboard-service"

# --- JOBS ---
jobs:
  # --- JOB 1: Build, Scan, Push Docker Images ---
  build-scan-push:
    name: Build, Scan, and Push Images
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Set up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4. Configure Docker for GAR
      - name: Configure Docker for GAR
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }} --quiet

      # 5. Build, Scan, and Push each service's Docker Image
      - name: Build, Scan, Push Services
        run: |
          IMAGE_TAG=${{ github.sha }} 

          for SERVICE in ${{ env.SERVICE_NAMES }}; do
            echo "--- Processing service: $SERVICE ---"

            # --- Define RELATIVE paths (relative to workspace root) ---
            SERVICE_PATH="./services/$SERVICE"
            DOCKERFILE_PATH="./services/$SERVICE/Dockerfile"
            BUILD_CONTEXT="./services/$SERVICE"
            IMAGE_NAME="${{ env.GAR_LOCATION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/$SERVICE"

            # Check if it's a Python service
            IS_PYTHON=false
            if [[ -f "$SERVICE_PATH/requirements.txt" ]]; then
              IS_PYTHON=true
            fi

            # --- CI: SAST for Python ---
            if $IS_PYTHON; then
              echo "Running SAST scans (Flake8 & Bandit) for $SERVICE..."
              pip install flake8 bandit
              flake8 $SERVICE_PATH/app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "Flake8 found issues (non-blocking)."
              bandit -r $SERVICE_PATH/app -ll -ii || echo "Bandit found issues (non-blocking)."
            else
               echo "Skipping Python SAST scans for $SERVICE..."
            fi

            # --- CI: Build Docker Image ---
            echo "Building Docker image for $SERVICE..."
            docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" \
              -f "${DOCKERFILE_PATH}" \
              "${BUILD_CONTEXT}"

            # --- CI: Container Vulnerability Scanning (Trivy via Docker) ---
            echo "Scanning image ${IMAGE_NAME}:${IMAGE_TAG} with Trivy..."
            # --- CRITICAL FIX: Mount and use .trivyignore for risk acceptance ---
            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v ${{ github.workspace }}/.trivyignore:/.trivyignore \
              aquasec/trivy:latest image \
              --exit-code 1 \
              --severity CRITICAL \
              --ignorefile /.trivyignore \
              "${IMAGE_NAME}:${IMAGE_TAG}"
            # --- END CRITICAL FIX ---

            # --- CI: Push Image to GAR ---
            echo "Pushing image ${IMAGE_NAME}:${IMAGE_TAG} to GAR..."
            docker push "${IMAGE_NAME}:${IMAGE_TAG}"

            echo "--- Finished processing $SERVICE ---"
          done

  # --- JOB 2: Deploy to GKE ---
  deploy-to-gke:
    name: Deploy to GKE
    needs: build-scan-push # Run only if build job succeeds
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Get GKE Credentials
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GCP_REGION }}

      # 4. Prepare K8s Manifests
      - name: Prepare K8s Manifests
        run: |
          IMAGE_TAG=${{ github.sha }}
          K8S_PATH="./k8s" 

          echo "Updating Kubernetes manifests in $K8S_PATH with Image Tag: $IMAGE_TAG"
          mkdir -p $K8S_PATH 

          find "$K8S_PATH" -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file; do
            echo "Processing $file..."
            sed -i "s|PLACEHOLDER_TAG|${IMAGE_TAG}|g" "$file"
            sed -i "s|PLACEHOLDER_PROJECT_ID|${{ env.GCP_PROJECT_ID }}|g" "$file"
            sed -i "s|PLACEHOLDER_REGION|${{ env.GCP_REGION }}|g" "$file"

            DB_USER_B64=$(echo -n "${{ secrets.DB_USER }}" | base64)
            DB_PASSWORD_B64=$(echo -n "${{ secrets.DB_PASSWORD }}" | base64)
            GEMINI_API_KEY_B64=$(echo -n "${{ secrets.GEMINI_API_KEY }}" | base64)

            sed -i "s|{{secrets.DB_USER}}|${DB_USER_B64}|g" "$file"
            sed -i "s|{{secrets.DB_PASSWORD}}|${DB_PASSWORD_B64}|g" "$file"
            sed -i "s|{{secrets.GEMINI_API_KEY}}|${GEMINI_API_KEY_B64}|g" "$file"
          done
          echo "Finished updating manifests."

      # 5. Deploy to GKE
      - name: Deploy to GKE
        run: |
          echo "Applying Kubernetes manifests from $K8S_PATH..."
          kubectl apply -f "$K8S_PATH"
          echo "Deployment initiated. Check GKE console for status."
